// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.3.1

package v1_session

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSessionRegisterSession = "/api.v1.session.Session/RegisterSession"

type SessionHTTPServer interface {
	RegisterSession(context.Context, *RegisterSessionRequest) (*RegisterSessionReply, error)
}

func RegisterSessionHTTPServer(s *http.Server, srv SessionHTTPServer) {
	r := s.Route("/")
	r.POST("/api/user/registerByMobile", _Session_RegisterSession0_HTTP_Handler(srv))
}

func _Session_RegisterSession0_HTTP_Handler(srv SessionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSessionRegisterSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterSession(ctx, req.(*RegisterSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterSessionReply)
		return ctx.Result(200, reply)
	}
}

type SessionHTTPClient interface {
	RegisterSession(ctx context.Context, req *RegisterSessionRequest, opts ...http.CallOption) (rsp *RegisterSessionReply, err error)
}

type SessionHTTPClientImpl struct {
	cc *http.Client
}

func NewSessionHTTPClient(client *http.Client) SessionHTTPClient {
	return &SessionHTTPClientImpl{client}
}

func (c *SessionHTTPClientImpl) RegisterSession(ctx context.Context, in *RegisterSessionRequest, opts ...http.CallOption) (*RegisterSessionReply, error) {
	var out RegisterSessionReply
	pattern := "/api/user/registerByMobile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSessionRegisterSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
