// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: v1/workOrder/workOrder.proto

package v1_workOrder

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workOrder_workOrder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workOrder_workOrder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_v1_workOrder_workOrder_proto_rawDescGZIP(), []int{0}
}

type EmptyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workOrder_workOrder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workOrder_workOrder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_v1_workOrder_workOrder_proto_rawDescGZIP(), []int{1}
}

type AddWorkOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Weigh   int64  `protobuf:"varint,3,opt,name=weigh,proto3" json:"weigh"`
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content"`
	Image   string `protobuf:"bytes,5,opt,name=image,proto3" json:"image"`
}

func (x *AddWorkOrderRequest) Reset() {
	*x = AddWorkOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workOrder_workOrder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddWorkOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkOrderRequest) ProtoMessage() {}

func (x *AddWorkOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workOrder_workOrder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkOrderRequest.ProtoReflect.Descriptor instead.
func (*AddWorkOrderRequest) Descriptor() ([]byte, []int) {
	return file_v1_workOrder_workOrder_proto_rawDescGZIP(), []int{2}
}

func (x *AddWorkOrderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddWorkOrderRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddWorkOrderRequest) GetWeigh() int64 {
	if x != nil {
		return x.Weigh
	}
	return 0
}

func (x *AddWorkOrderRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddWorkOrderRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type GetWorkOrderListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type"`
	Status int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status"`
	Page   int64  `protobuf:"varint,3,opt,name=page,proto3" json:"page"`
}

func (x *GetWorkOrderListRequest) Reset() {
	*x = GetWorkOrderListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workOrder_workOrder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkOrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkOrderListRequest) ProtoMessage() {}

func (x *GetWorkOrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workOrder_workOrder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkOrderListRequest.ProtoReflect.Descriptor instead.
func (*GetWorkOrderListRequest) Descriptor() ([]byte, []int) {
	return file_v1_workOrder_workOrder_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkOrderListRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetWorkOrderListRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetWorkOrderListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetWorkOrderListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64                                      `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Page  int64                                      `protobuf:"varint,2,opt,name=page,proto3" json:"page"`
	List  []*GetWorkOrderListReply_WorkOrderListItem `protobuf:"bytes,3,rep,name=list,proto3" json:"list"`
}

func (x *GetWorkOrderListReply) Reset() {
	*x = GetWorkOrderListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workOrder_workOrder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkOrderListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkOrderListReply) ProtoMessage() {}

func (x *GetWorkOrderListReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workOrder_workOrder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkOrderListReply.ProtoReflect.Descriptor instead.
func (*GetWorkOrderListReply) Descriptor() ([]byte, []int) {
	return file_v1_workOrder_workOrder_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkOrderListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetWorkOrderListReply) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetWorkOrderListReply) GetList() []*GetWorkOrderListReply_WorkOrderListItem {
	if x != nil {
		return x.List
	}
	return nil
}

type GetWorkOrderDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *GetWorkOrderDetailRequest) Reset() {
	*x = GetWorkOrderDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workOrder_workOrder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkOrderDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkOrderDetailRequest) ProtoMessage() {}

func (x *GetWorkOrderDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workOrder_workOrder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkOrderDetailRequest.ProtoReflect.Descriptor instead.
func (*GetWorkOrderDetailRequest) Descriptor() ([]byte, []int) {
	return file_v1_workOrder_workOrder_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkOrderDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWorkOrderDetailReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       string                     `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Title      string                     `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Type       string                     `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`
	Weigh      int64                      `protobuf:"varint,4,opt,name=weigh,proto3" json:"weigh"`
	WeighName  string                     `protobuf:"bytes,5,opt,name=weighName,proto3" json:"weighName"`
	Status     int64                      `protobuf:"varint,6,opt,name=status,proto3" json:"status"`
	StatusName string                     `protobuf:"bytes,7,opt,name=statusName,proto3" json:"statusName"`
	CreateTime string                     `protobuf:"bytes,8,opt,name=createTime,proto3" json:"createTime"`
	ReplyList  []*WorkOrderDetailListItem `protobuf:"bytes,9,rep,name=replyList,proto3" json:"replyList"`
}

func (x *GetWorkOrderDetailReply) Reset() {
	*x = GetWorkOrderDetailReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workOrder_workOrder_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkOrderDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkOrderDetailReply) ProtoMessage() {}

func (x *GetWorkOrderDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workOrder_workOrder_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkOrderDetailReply.ProtoReflect.Descriptor instead.
func (*GetWorkOrderDetailReply) Descriptor() ([]byte, []int) {
	return file_v1_workOrder_workOrder_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorkOrderDetailReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetWorkOrderDetailReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetWorkOrderDetailReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetWorkOrderDetailReply) GetWeigh() int64 {
	if x != nil {
		return x.Weigh
	}
	return 0
}

func (x *GetWorkOrderDetailReply) GetWeighName() string {
	if x != nil {
		return x.WeighName
	}
	return ""
}

func (x *GetWorkOrderDetailReply) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetWorkOrderDetailReply) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *GetWorkOrderDetailReply) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *GetWorkOrderDetailReply) GetReplyList() []*WorkOrderDetailListItem {
	if x != nil {
		return x.ReplyList
	}
	return nil
}

type WorkOrderDetailListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content    string `protobuf:"bytes,1,opt,name=content,proto3" json:"content"`
	CreateTime string `protobuf:"bytes,2,opt,name=createTime,proto3" json:"createTime"`
	Type       int64  `protobuf:"varint,3,opt,name=type,proto3" json:"type"`
	Look       int64  `protobuf:"varint,4,opt,name=look,proto3" json:"look"`
}

func (x *WorkOrderDetailListItem) Reset() {
	*x = WorkOrderDetailListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workOrder_workOrder_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkOrderDetailListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkOrderDetailListItem) ProtoMessage() {}

func (x *WorkOrderDetailListItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workOrder_workOrder_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkOrderDetailListItem.ProtoReflect.Descriptor instead.
func (*WorkOrderDetailListItem) Descriptor() ([]byte, []int) {
	return file_v1_workOrder_workOrder_proto_rawDescGZIP(), []int{7}
}

func (x *WorkOrderDetailListItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WorkOrderDetailListItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *WorkOrderDetailListItem) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *WorkOrderDetailListItem) GetLook() int64 {
	if x != nil {
		return x.Look
	}
	return 0
}

type GetWorkOrderListReply_WorkOrderListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Code       string `protobuf:"bytes,2,opt,name=code,proto3" json:"code"`
	Type       string `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`
	Status     int64  `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
	StatusName string `protobuf:"bytes,5,opt,name=statusName,proto3" json:"statusName"`
	CreateTime string `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime"`
}

func (x *GetWorkOrderListReply_WorkOrderListItem) Reset() {
	*x = GetWorkOrderListReply_WorkOrderListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workOrder_workOrder_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkOrderListReply_WorkOrderListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkOrderListReply_WorkOrderListItem) ProtoMessage() {}

func (x *GetWorkOrderListReply_WorkOrderListItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workOrder_workOrder_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkOrderListReply_WorkOrderListItem.ProtoReflect.Descriptor instead.
func (*GetWorkOrderListReply_WorkOrderListItem) Descriptor() ([]byte, []int) {
	return file_v1_workOrder_workOrder_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetWorkOrderListReply_WorkOrderListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetWorkOrderListReply_WorkOrderListItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetWorkOrderListReply_WorkOrderListItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetWorkOrderListReply_WorkOrderListItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetWorkOrderListReply_WorkOrderListItem) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *GetWorkOrderListReply_WorkOrderListItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

var File_v1_workOrder_workOrder_proto protoreflect.FileDescriptor

var file_v1_workOrder_workOrder_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x77,
	0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x85, 0x01, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x57, 0x6f, 0x72,
	0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x65, 0x69, 0x67, 0x68, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x59, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0xb6, 0x02, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x4d, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0xa3, 0x01, 0x0a, 0x11,
	0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x2b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xac,
	0x02, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x65, 0x69, 0x67, 0x68, 0x12, 0x1c,
	0x0a, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x77, 0x65, 0x69, 0x67, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x47, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x7b, 0x0a,
	0x17, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6f, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x6f, 0x6f, 0x6b, 0x32, 0xb4, 0x03, 0x0a, 0x09, 0x77,
	0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x7b, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x57,
	0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x57,
	0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x26, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x20, 0x22, 0x1b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72, 0x6b,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x61, 0x64, 0x64, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x3a, 0x01, 0x2a, 0x12, 0x8f, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72,
	0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x27,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72,
	0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x97, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x57,
	0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x2b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x12, 0x21,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x67,
	0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x42, 0x1b, 0x5a, 0x19, 0x63, 0x64, 0x6e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_workOrder_workOrder_proto_rawDescOnce sync.Once
	file_v1_workOrder_workOrder_proto_rawDescData = file_v1_workOrder_workOrder_proto_rawDesc
)

func file_v1_workOrder_workOrder_proto_rawDescGZIP() []byte {
	file_v1_workOrder_workOrder_proto_rawDescOnce.Do(func() {
		file_v1_workOrder_workOrder_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_workOrder_workOrder_proto_rawDescData)
	})
	return file_v1_workOrder_workOrder_proto_rawDescData
}

var file_v1_workOrder_workOrder_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_workOrder_workOrder_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),                            // 0: api.v1.workOrder.EmptyRequest
	(*EmptyReply)(nil),                              // 1: api.v1.workOrder.EmptyReply
	(*AddWorkOrderRequest)(nil),                     // 2: api.v1.workOrder.AddWorkOrderRequest
	(*GetWorkOrderListRequest)(nil),                 // 3: api.v1.workOrder.GetWorkOrderListRequest
	(*GetWorkOrderListReply)(nil),                   // 4: api.v1.workOrder.GetWorkOrderListReply
	(*GetWorkOrderDetailRequest)(nil),               // 5: api.v1.workOrder.GetWorkOrderDetailRequest
	(*GetWorkOrderDetailReply)(nil),                 // 6: api.v1.workOrder.GetWorkOrderDetailReply
	(*WorkOrderDetailListItem)(nil),                 // 7: api.v1.workOrder.WorkOrderDetailListItem
	(*GetWorkOrderListReply_WorkOrderListItem)(nil), // 8: api.v1.workOrder.GetWorkOrderListReply.WorkOrderListItem
}
var file_v1_workOrder_workOrder_proto_depIdxs = []int32{
	8, // 0: api.v1.workOrder.GetWorkOrderListReply.list:type_name -> api.v1.workOrder.GetWorkOrderListReply.WorkOrderListItem
	7, // 1: api.v1.workOrder.GetWorkOrderDetailReply.replyList:type_name -> api.v1.workOrder.WorkOrderDetailListItem
	2, // 2: api.v1.workOrder.workOrder.AddWorkOrder:input_type -> api.v1.workOrder.AddWorkOrderRequest
	3, // 3: api.v1.workOrder.workOrder.GetWorkOrderList:input_type -> api.v1.workOrder.GetWorkOrderListRequest
	5, // 4: api.v1.workOrder.workOrder.GetWorkOrderDetail:input_type -> api.v1.workOrder.GetWorkOrderDetailRequest
	1, // 5: api.v1.workOrder.workOrder.AddWorkOrder:output_type -> api.v1.workOrder.EmptyReply
	4, // 6: api.v1.workOrder.workOrder.GetWorkOrderList:output_type -> api.v1.workOrder.GetWorkOrderListReply
	6, // 7: api.v1.workOrder.workOrder.GetWorkOrderDetail:output_type -> api.v1.workOrder.GetWorkOrderDetailReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_workOrder_workOrder_proto_init() }
func file_v1_workOrder_workOrder_proto_init() {
	if File_v1_workOrder_workOrder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_workOrder_workOrder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workOrder_workOrder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workOrder_workOrder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddWorkOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workOrder_workOrder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkOrderListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workOrder_workOrder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkOrderListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workOrder_workOrder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkOrderDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workOrder_workOrder_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkOrderDetailReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workOrder_workOrder_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkOrderDetailListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workOrder_workOrder_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkOrderListReply_WorkOrderListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_workOrder_workOrder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_workOrder_workOrder_proto_goTypes,
		DependencyIndexes: file_v1_workOrder_workOrder_proto_depIdxs,
		MessageInfos:      file_v1_workOrder_workOrder_proto_msgTypes,
	}.Build()
	File_v1_workOrder_workOrder_proto = out.File
	file_v1_workOrder_workOrder_proto_rawDesc = nil
	file_v1_workOrder_workOrder_proto_goTypes = nil
	file_v1_workOrder_workOrder_proto_depIdxs = nil
}
